version: '3'
services:
  node:
    build: .
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./user_app:/home/node/app
      - ./configs/sshd_config:/etc/ssh/sshd_config

  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 10081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

